apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsa-signature-demo
  namespace: rsa-signature-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsa-signature-demo
  template:
    metadata:
      labels:
        app: rsa-signature-demo
    spec:
      initContainers:
      - name: extract-files
        image: alpine:latest
        command: ['sh', '-c', 'cd /usr/share/nginx/html && tar -xzf /tmp/dist.tar.gz']
        volumeMounts:
        - name: static-files
          mountPath: /usr/share/nginx/html
        - name: dist-tar
          mountPath: /tmp
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: static-files
        emptyDir: {}
      - name: dist-tar
        configMap:
          name: rsa-signature-files
